apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: gziphello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/targetBurstCapacity: "0"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: ko://github.com/julz/gziphello
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1b"
